### PR TITLE
Migration to Go module(vgo)

### PR DESCRIPTION
**Pull request by themontem**
- [x] Remove `vendor` folder

### CODE REVIEW

**Comment by marco-m** [comment]
Hello @brian-brazil , the Prometheus repo now has go mod support :-)

**Comment by brian-brazil** [comment]
Can you update this, and vendor everything in?

**Comment by themontem** [comment]
@brian-brazil Done.

**Comment by brian-brazil** [comment]
You're still deleting the vendor directory

**Comment by brian-brazil** [comment]
It's what we're doing in Prometheus.

**Comment by brian-brazil** [comment]
This is obsolete.

**Pull request closed without merging**
