### PR TITLE
Add option to whitelist ports

### PR DESCRIPTION
**Pull request by sezuan**
Maybe it makes sense to whitelist ports on each client which knows the local exporters instead of maintaining large ACLs on a proxy.

### CODE REVIEW

**Comment by brian-brazil** [comment]
What is the attack vector you are worried about?

**Comment by sezuan** [comment]
As far as I understood, anyone who can connect to the proxy can connect to arbitrary ports on the client. In that case it might be possible to bypass ip based firewalls since the connection comes from localhost.

**Comment by brian-brazil** [comment]
We generally don't provide auth mechanisms in Prometheus components, as there's just too many ways to do this. I'd suggest locking down the proxy or taking advantage of the fact that iptables can use uids.

**Comment by sezuan** [comment]
Okay, thanks!

**Pull request closed without merging**
