### PR TITLE
Strict mode to enforce FQDN

### PR DESCRIPTION
**Pull request by glaslos**
Just to add one more contender to the discussion :)
Motivation for this implementation is to enforce the concept of the client being just a representation of a single system. I assume we could even enforce the HTTP verb by default by I'm not sure if there are prometheus targets using a different verb than GET.
Instead of using a white list or some form of regex, this strict mode enforces the host to be the FQDN announced by the client.

### CODE REVIEW

**Comment by brian-brazil** [comment]
We should probably be rejecting queries that don't match these always, though non-GET requests will be a thing at some point due to URL length limits.

**Comment by glaslos** [comment]
Cool, thanks for the feedback, I dropped enforcing GET and reject scrapes that don't match the FQDN in strict mode.
I did also a bit of refactoring for error handling and added a couple of tests.

**Comment by brian-brazil** [comment]
My point was that this shouldn't be configurable, we should always check this.

**Comment by glaslos** [comment]
Yeah, I had the same thought but you would might break a lot of existing deployments. But there hasn't been a release yet so everything is allowed in love and war?

**Comment by brian-brazil** [comment]
How would it break existing deployments?

**Comment by glaslos** [comment]
Ah, my bad. Because the client announces only the fqdn the proxy should only forward scrapes for the fqdn hence there is no reason for them to not match. I will make that change.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
